services:
  chatbot:
    build: .
    hostname: chatbot
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: always
    networks:
      - chatbot-network
    depends_on:
      - db
      - ollama

  db:
    image: pgvector/pgvector:pg17
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatbot-network

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    networks:
      - chatbot-network
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  pgdata:


networks:
  chatbot-network:
    external: true
